services:
    app.form.registration:
        class: Techlancaster\Bundle\WebBundle\Form\RegistrationFormType
        arguments: ['Techlancaster\Bundle\WebBundle\Entity\User']
        tags:
            - { name: form.type, alias: tl_user_registration }
